---
extends:
  - xo
  - xo-react/space
  - prettier
  - prettier/react
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended

plugins:
  - react-hooks
  - jest

env:
  browser: true
  jest/globals: true

rules:
  capitalized-comments:
    - error
    - never
    - ignorePattern: TODO|NOTE|FIXME
  no-unused-expressions:
    - error
    - allowTaggedTemplates: true
  react-hooks/rules-of-hooks: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always

# resolve webpack-aliases through node-resolver, were not detected otherwise
settings:
  import/resolver:
    node:
      paths:
        - src
