---
extends:
  - xo
  - xo-react/space
  - prettier
  - prettier/react
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - react-hooks

env:
  'browser': true

rules:
  no-unused-expressions: ['error', { 'allowTaggedTemplates': true }]
  react-hooks/rules-of-hooks: 'error'
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always

settings:
  import/resolver:
    node:
      paths:
        - src
